version: '3'

services:
  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  compiler:
    build: ./compiler/backend
    container_name: compiler-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DOCKER_ENV=true
      - SKIP_REDIS=FALSE
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongodb:27017/algo-auth
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  crud:
    build: ./crud/backend
    container_name: crud-service
    ports:
      - "2000:2000"
    environment:
      - MONGOURL=mongodb://mongodb:27017/algo-auth
    networks:
      - app-network
    restart: unless-stopped

  auth:
    build: ./backend
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/algo-auth
      - JWT_SECRET=your_jwt_secret_here
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:





