services:
  - type: web
    name: online-judge-compiler
    env: node
    buildCommand: cd compiler/backend && npm install
    startCommand: cd compiler/backend && node index.js
    envVars:
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://online-judge-sandy.vercel.app
      - key: SKIP_REDIS
        value: TRUE
      - key: CORS_ORIGIN
        value: https://online-judge-sandy.vercel.app
      - key: NODE_ENV
        value: production

